"""empty message

Revision ID: 665a24b0ed37
Revises: ad1ac6275234
Create Date: 2018-05-29 21:18:39.019017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665a24b0ed37'
down_revision = 'ad1ac6275234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_confirm_on'), 'users', ['confirm_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_confirm_on'), table_name='users')
    op.drop_column('users', 'confirm_on')
    # ### end Alembic commands ###
