"""empty message

Revision ID: ad1ac6275234
Revises: 94be5051d7f3
Create Date: 2018-05-24 15:36:27.689951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1ac6275234'
down_revision = '94be5051d7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campgrounds_name', table_name='campgrounds')
    op.create_index(op.f('ix_campgrounds_name'), 'campgrounds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campgrounds_name'), table_name='campgrounds')
    op.create_index('ix_campgrounds_name', 'campgrounds', ['name'], unique=True)
    # ### end Alembic commands ###
